version: '{build}'

branches:
  only:
    - master

image:
  - Ubuntu2004

install:
  - ps: git submodule init
  - ps: git submodule update
  - ps: nproc
  - ps: pwd
  - pushd ~
  - svn checkout -r 3120 https://svn.code.sf.net/p/tass64/code/trunk tass64-code
  - cd ~/tass64-code && make -j$(nproc)
  - popd
  - ps: $env:RELEASE_NAME = $(git log -1 --format=%cd-%h --date=format:%Y%m%d-%H%M%S $env:APPVEYOR_REPO_COMMIT)

build_script:
  - ps: $env:OUTPUT_LST_ARCHIVE="acorn-mos-disassembly-lst."+$env:RELEASE_NAME+".zip"
  - ps: $env:OUTPUT_NT_ARCHIVE="acorn-mos-disassembly-NT."+$env:RELEASE_NAME+".zip"
  - ps: make VERBOSE=1 TASSCMD=$HOME/tass64-code/64tass
  - pushd build
  - zip -9r "../$OUTPUT_NT_ARCHIVE" 320nt 350nt
  - zip -9 "../$OUTPUT_LST_ARCHIVE" *.lst
  - popd
  - zip -9j "$OUTPUT_NT_ARCHIVE" "docs/README.txt"
  - zip- 9j "$OUTPUT_LST_ARCHIVE" "docs/README.txt"
  - env
    
artifacts:
  - path: $(OUTPUT_LST_ARCHIVE)
    name: lst_archive
  - path: $(OUTPUT_NT_ARCHIVE)
    name: nt_archive

deploy:
  - release: $(RELEASE_NAME)
    description: See https://github.com/tom-seddon/acorn_mos_disassembly
      
    provider: GitHub
    auth_token:
      secure: fbUFdJ9CBwsYJ43oEC7AZO8FDuTtwlFOo2S953oBUhew7Qwo/+AZVCIjhSsV0S3M
    artifact: lst_archive,nt_archive
    draft: false
    prerelease: false
