* OSBYTEs

** By number

OSBYTE 0 (&00) Display MOS version [MasRef D.2-18]
OSBYTE 1 (&01) Write user flag [MasRef D.2-18]
OSBYTE 2 (&02) Specify input stream [MasRef D.2-18]
OSBYTE 3 (&03) Specify output stream [MasRef D.2-19]
OSBYTE 4 (&04) Enable/disable cursor editing [MasRef D.2-19]
OSBYTE 5 (&05) Write printer driver type [MasRef D.2-20]
OSBYTE 6 (&06) Write printer ignore character [MasRef D.2-21]
OSBYTE 7 (&07) Write RS423 receive rate [MasRef D.2-21]
OSBYTE 8 (&08) Write RS423 transmit rate [MasRef D.2-22]
OSBYTE 9 (&09) Write duration of first colour [MasRef D.2-22]
OSBYTE 10 (&0A) Write duration of second colour [MasRef D.2-22]
OSBYTE 11 (&0B) Write keyboard auto-repeat delay [MasRef D.2-22]
OSBYTE 12 (&0C) Write keyboard auto-repeat rate [MasRef D.2-23]
OSBYTE 13 (&0D) Disable event [MasRef D.2-23]
OSBYTE 14 (&0E) Enable event [MasRef D.2-24]
OSBYTE 15 (&0F) Flush buffer [MasRef D.2-24]
OSBYTE 16 (&10) Write number of ADC channels [MasRef D.2-25]
OSBYTE 17 (&11) Write next ADC channel to be sampled [MasRef D.2-25]
OSBYTE 18 (&12) Reset soft keys [MasRef D.2-26]
OSBYTE 19 (&13) Wait for vertical sync [MasRef D.2-26]
OSBYTE 20 (&14) Restore default font definitions [MasRef D.2-26]
OSBYTE 21 (&15) Flush selected buffer [MasRef D.2-27]
OSBYTE 22 (&16) Increment ROM polling semaphore[MasRef D.2-27]
OSBYTE 23 (&17) Decrement ROM polling semaphore[MasRef D.2-27]
OSBYTE 24 (&18) is reserved. [MasRef D.2-28]
OSBYTE 25 (&19) Restore a group of font definitions [MasRef D.2-28]
OSBYTE 26 (&1A) – 67 (&43) are currently unused. [MasRef D.2-28]
OSBYTE 68 (&44) Test RAM presence [MasRef D.2-28]
OSBYTE 69 (&45) Test pseudo/absolute use of bank [MasRef D.2-29]
OSBYTE 70 (&45) – 106 (&6A) are currently unused. [MasRef D.2-29]
OSBYTE 107 (&6B) Write 1MHz bus selection status [MasRef D.2-29]
OSBYTE 108 (&6C) Write usage of main/shadow memory [MasRef D.2-30]
OSBYTE 109 (&6D) Make temporary Filing System permanent [MasRef D.2-30]
OSBYTE 110 (&6E) is currently unused. [MasRef D.2-31]
OSBYTE 111 (&6F) is currently unused. [MasRef D.2-31]
OSBYTE 114 (&72) Write usage of shadow memory [MasRef D.2-32]
OSBYTE 115 (&73) is currently unused. [MasRef D.2-32]
OSBYTE 116 (&74) is currently unused. [MasRef D.2-32]
OSBYTE 117 (&75) Read VDU status [MasRef D.2-32]
OSBYTE 118 (&76) Reflect keyboard status in keyboard [MasRef D.2-33]
OSBYTE 119 (&77) Close all *SPOOL/*SPOOLON or [MasRef D.2-33]
OSBYTE 120 (&78) Write keys pressed information [MasRef D.2-33]
OSBYTE 121 (&79) Keyboard scan [MasRef D.2-35]
OSBYTE 122 (&7A) Keyboard scan from 16 decimal [MasRef D.2-36]
OSBYTE 123 (&7B) Inform MOS of printer driver going dormant [MasRef D.2-36]
OSBYTE 124 (&7C) Clear escape condition [MasRef D.2-36]
OSBYTE 125 (&7D) Set escape condition [MasRef D.2-36]
OSBYTE 126 (&7E) Acknowledge escape condition [MasRef D.2-37]
OSBYTE 127 (&7F) Check for end of file on an opened file [MasRef D.2-37]
OSBYTE 128 (&80) Read ADC channel or get buffer status [MasRef D.2-37]
OSBYTE 129 (&81) Read key with time limit [MasRef D.2-38]
OSBYTE 130 (&82) Read machine high order address [MasRef D.2-40]
OSBYTE 131 (&83) Read Operating System High Water Mark (OSHWM) [MasRef D.2-40]
OSBYTE 132 (&84) Read top of user RAM [MasRef D.2-40]
OSBYTE 133 (&85) Read top of user RAM for given mode [MasRef D.2-41]
OSBYTE 134 (&86) Read text cursor position [MasRef D.2-41]
OSBYTE 135 (&87) Read screen mode and character at [MasRef D.2-42]
OSBYTE 136 (&88) Execute user code [MasRef D.2-42]
OSBYTE 137 (&89) Switch cassette motor relay [MasRef D.2-42]
OSBYTE 138 (&8A) Insert character code into buffer [MasRef D.2-43]
OSBYTE 139 (&8B) Write Filing System options [MasRef D.2-43]
OSBYTE 140 (&8C) Select Cassette Filing System [MasRef D.2-43]
OSBYTE 141 (&8D) Select ROM Filing System [MasRef D.2-43]
OSBYTE 142 (&8E) Enter language ROM [MasRef D.2-44]
OSBYTE 143 (&8F) Issue paged ROM service request [MasRef D.2-44]
OSBYTE 144 (&90) Set vertical screen shift and interlace [MasRef D.2-44]
OSBYTE 145 (&91) Get character from buffer [MasRef D.2-45]
OSBYTE 146 (&92) Read from FRED (&FC00 – &FCFF) [MasRef D.2-45]
OSBYTE 147 (&93) Write to FRED (&FC00 – &FCFF) [MasRef D.2-45]
OSBYTE 148 (&94) Read from JIM (&FD00 – &FDFF) [MasRef D.2-45]
OSBYTE 149 (&95) Write to JIM (&FD00 – &FDFF) [MasRef D.2-45]
OSBYTE 150 (&96) Read from SHEILA (&FE00 – &FEFF) [MasRef D.2-45]
OSBYTE 151 (&97) Write to SHEILA (&FE00 – &FEFF) [MasRef D.2-45]
OSBYTE 152 (&98) Examine buffer status [MasRef D.2-45]
OSBYTE 153 (&99) Insert character code into buffer [MasRef D.2-46]
OSBYTE 154 (&9A) Write video ULA control register [MasRef D.2-46]
OSBYTE 155 (&9B) Write to video ULA palette register and [MasRef D.2-47]
OSBYTE 156 (&9C) Read/write serial ACIA control [MasRef D.2-47]
OSBYTE 157 (&9D) Write byte across Tube [MasRef D.2-48]
OSBYTE 158 (&9E) reserved for the speech system. [MasRef D.2-49]
OSBYTE 159 (&9F) reserved for the speech system. [MasRef D.2-49]
OSBYTE 160 (&A0) Read VDU variable value [MasRef D.2-49]
OSBYTE 161 (&A1) Read CMOS RAM [MasRef D.2-49]
OSBYTE 162 (&A2) Write CMOS RAM [MasRef D.2-49]
OSBYTE 163 (&A3) is reserved for applications software. [MasRef D.2-50]
OSBYTE 164 (&A4) Check processor type [MasRef D.2-50]
OSBYTE 165 (&A5) Read output cursor position [MasRef D.2-50]
OSBYTE 166 (&A6) Read start address of MOS variables [MasRef D.2-50]
OSBYTE 167 (&A7) Read start address of MOS variablespointer table  [MasRef D.2-50]
OSBYTE 168 (&A8) Read address of ROM pointer table [MasRef D.2-51]
OSBYTE 169 (&A9) Read address of ROM pointer table [MasRef D.2-51]
OSBYTE 170 (&AA) Read address of ROM information table [MasRef D.2-51]
OSBYTE 171 (&AB) Read address of ROM information table [MasRef D.2-51]
OSBYTE 172 (&AC) Read address of keyboard translation table [MasRef D.2-52]
OSBYTE 173 (&AD) Read address of keyboard translation table [MasRef D.2-52]
OSBYTE 174 (&AE) Read address of VDU variables origin [MasRef D.2-52]
OSBYTE 175 (&AF) Read address of VDU variables origin [MasRef D.2-52]
OSBYTE 176 (&B0) Read/Write CFS timeout counter [MasRef D.2-52]
OSBYTE 177 (&B1) Read/write input source [MasRef D.2-53]
OSBYTE 178 (&B2) Read/write keyboard semaphore [MasRef D.2-53]
OSBYTE 179 (&B3) Read/write ROM polling semaphore [MasRef D.2-54]
OSBYTE 180 (&B4) Read/write Operating System High [MasRef D.2-54]
OSBYTE 181 (&B5) Read/write RS243 input interpretation [MasRef D.2-54]
OSBYTE 182 (&B6) Read NOIGNORE state [MasRef D.2-55]
OSBYTE 183 (&B7) Read/write cassette/ROM filing system [MasRef D.2-55]
OSBYTE 184 (&B8) Read OS copy of video ULA control [MasRef D.2-56]
OSBYTE 185 (&B9) Read OS copy of video ULA palette [MasRef D.2-56]
OSBYTE 186 (&BA) Read ROM number active at last BRK [MasRef D.2-56]
OSBYTE 187 (&BB) Read ROM number of socket [MasRef D.2-57]
OSBYTE 188 (&BC) Read current ADC channel number [MasRef D.2-57]
OSBYTE 189 (&BD) Read maximum ADC channel number [MasRef D.2-57]
OSBYTE 190 (&BE) Read/write ADC conversion type [MasRef D.2-58]
OSBYTE 191 (&BF) Read/write RS423 busy flag [MasRef D.2-58]
OSBYTE 192 (&C0) Read serial ACIA control register [MasRef D.2-58]
OSBYTE 193 (&C1) Read/write flash counter [MasRef D.2-59]
OSBYTE 194 (&C2) Read/write duration of first colour [MasRef D.2-59]
OSBYTE 195 (&C3) Read/write duration of second colour [MasRef D.2-60]
OSBYTE 196 (&C4) Read/write keyboard auto-repeat delay [MasRef D.2-60]
OSBYTE 197 (&C5) Read/write keyboard auto-repeat rate [MasRef D.2-60]
OSBYTE 198 (&C6) Read/write *EXEC file handle [MasRef D.2-61]
OSBYTE 199 (&C7) Read/write *SPOOL file handle [MasRef D.2-62]
OSBYTE 200 (&C8) Read/write BREAK and ESCAPE effect [MasRef D.2-62]
OSBYTE 201 (&C9) Read/write keyboard status [MasRef D.2-63]
OSBYTE 202 (&CA) Read/write keyboard status byte [MasRef D.2-63]
OSBYTE 203 (&CB) Read/write RS423 input buffer [MasRef D.2-64]
OSBYTE 204 (&CC) Read/write RS423 ignore flag [MasRef D.2-65]
OSBYTE 205 (&CD) Read/write RS423 destination [MasRef D.2-65]
OSBYTE 206 (&CE) Read/write Econet OS call interception [MasRef D.2-66]
OSBYTE 207 (&CF) Read/write Econet input interpretation [MasRef D.2-66]
OSBYTE 208 (&D0) Read write Econet output [MasRef D.2-67]
OSBYTE 209 (&D1) is reserved for the speech system [MasRef D.2-67]
OSBYTE 210 (&D2) Read/write sound suppression status [MasRef D.2-67]
OSBYTE 211 (&D3) Read/write BELL channel [MasRef D.2-67]
OSBYTE 212 (&D4) Read/write BELL sound information [MasRef D.2-68]
OSBYTE 213 (&D5) Read/write BELL frequency [MasRef D.2-69]
OSBYTE 214 (&D6) Read/write BELL duration [MasRef D.2-69]
OSBYTE 215 (&D7) Read/write startup message [MasRef D.2-69]
OSBYTE 216 (&D8) Read/write length of soft key string [MasRef D.2-70]
OSBYTE 217 (&D9) Read/write paged mode line count [MasRef D.2-71]
OSBYTE 218 (&DA) Read/write bytes in VDU queue [MasRef D.2-71]
OSBYTE 219 (&DB) Read/write TAB key code [MasRef D.2-72]
OSBYTE 220 (&DC) Read/write ESCAPE character [MasRef D.2-72]
OSBYTE 221 (&DD) Read/write interpretation of input values 192-207 [MasRef D.2-73]
OSBYTE 222 (&DE) Read/write interpretation of input values 208-223 [MasRef D.2-73]
OSBYTE 223 (&DF) Read/write interpretation of input values 224-239 [MasRef D.2-73]
OSBYTE 224 (&E0) Read/write interpretation of input values 240-255 [MasRef D.2-73]
OSBYTE 225 (&E1) Read/write soft key interpretation [MasRef D.2-74]
OSBYTE 226 (&E2) Read/write SHIFT+soft key interpretation [MasRef D.2-74]
OSBYTE 227 (&E3) Read/write CTRL+soft key interpretation [MasRef D.2-74]
OSBYTE 228 (&E4) Read/write SHIFT+CTRL+soft key interpretation [MasRef D.2-74]
OSBYTE 229 (&E5) Read/write ESCAPE key status [MasRef D.2-75]
OSBYTE 230 (&E6) Read/write ESCAPE effects [MasRef D.2-75]
OSBYTE 231 (&E7) Read/write IRQ bit mask for user 6522 [MasRef D.2-76]
OSBYTE 232 (&E8) Read/write IRQ bit mask for 6850 [MasRef D.2-76]
OSBYTE 233 (&E9) Read write IRQ bit mask for system [MasRef D.2-76]
OSBYTE 234 (&EA) Read flag indicating Tube presence [MasRef D.2-76]
OSBYTE 235 (&EB) is reserved for the speech system. [MasRef D.2-77]
OSBYTE 236 (&EC) Read/write character destination status [MasRef D.2-77]
OSBYTE 237 (&ED) Read/write cursor editing status [MasRef D.2-77]
OSBYTE 238 (&EE) Read/write numeric keypad [MasRef D.2-78]
OSBYTE 239 (&EF) Read/write *SHADOW state [MasRef D.2-78]
OSBYTE 240 (&F0) Read country flag [MasRef D.2-79]
OSBYTE 241 (&F1) Read/write user flag [MasRef D.2-79]
OSBYTE 242 (&F2) Read copy of serial processor ULA [MasRef D.2-80]
OSBYTE 243 (&F3) Read timer switch state [MasRef D.2-80]
OSBYTE 244 (&F4) Read/write soft key consistency flag [MasRef D.2-81]
OSBYTE 245 (&F5) Read printer driver type [MasRef D.2-81[
OSBYTE 246 (&F6) Read/write printer ignore character [MasRef D.2-81]
OSBYTE 247 (&F7) Read/write BREAK intercept vector [MasRef D.2-82]
OSBYTE 248 (&F7) Read/write BREAK intercept vector [MasRef D.2-82]
OSBYTE 249 (&F7) Read/write BREAK intercept vector [MasRef D.2-82]
OSBYTE 250 (&FA) Read memory written by VDU driver [MasRef D.2-82]
OSBYTE 251 (&FB) Read memory displayed [MasRef D.2-83]
OSBYTE 252 (&FC) Read/write current language ROM number [MasRef D.2-83]
OSBYTE 253 (&FD) Read last BREAK type [MasRef D.2-83]
OSBYTE 254 (&FE) Set effect of SHIFT on numeric keypad [MasRef D.2-84]
OSBYTE 255 (&FF) Read/write startup options [MasRef D.2-84]

* Commands

| Command   | 320           | 500           | 510           | 511           |
|-----------+---------------+---------------+---------------+---------------|
|           | $f1e5 $00 $03 | $f293 $00 $03 | $f293 $00 $03 | $f29c $00 $03 |
| ADFS      | $85af $00 $00 | $85c2 $00 $00 | $85ff $00 $00 | $85ff $00 $00 |
| APPEND    | $9014 $80 $00 | $91e1 $80 $00 | $921e $80 $00 | $921e $80 $00 |
| BASIC     | $85a6 $00 $00 | $85b8 $00 $00 | $85f5 $00 $00 | $85f5 $00 $00 |
| BUILD     | $900f $80 $00 | $91dc $80 $00 | $9219 $80 $00 | $9219 $80 $00 |
| CAT       | $f1e5 $80 $05 | $f293 $80 $05 | $f293 $80 $05 | $f29c $80 $05 |
| CLOSE     | $937c $00 $ff | $9558 $00 $ff | $967f $00 $ff | $967f $00 $ff |
| CODE      | $93eb $00 $88 | $95c7 $00 $88 | $9600 $00 $88 | $9600 $00 $88 |
| CONFIGURE | $887a $00 $ff | $8856 $00 $80 | $8893 $00 $80 | $8893 $00 $80 |
| CREATE    | $9318 $80 $07 | $94f4 $80 $07 | $9531 $80 $07 | $9531 $80 $07 |
| DELETE    | $946a $80 $00 | $9646 $80 $00 | $9695 $80 $00 | $9695 $80 $00 |
| DUMP      | $8f42 $80 $00 | $910f $80 $00 | $914c $80 $00 | $914c $80 $00 |
| EX        | $f1e5 $80 $09 | $f293 $80 $09 | $f293 $80 $09 | $f29c $80 $09 |
| EXEC      | $a591 $80 $00 | $a98d $80 $00 | $a9fd $80 $00 | $aa00 $80 $00 |
| FX        | $93e5 $00 $ff | $95c1 $00 $ff | $95fa $00 $ff | $95fa $00 $ff |
| GO        | $92f5 $00 $ff | $94d1 $00 $ff | $950e $00 $ff | $950e $00 $ff |
| GOIO      | $92fd $00 $ff | $94d9 $00 $ff | $9516 $00 $ff | $9516 $00 $ff |
| HELP      | $85ca $00 $ff | $85dd $00 $ff | $861a $00 $ff | $861a $00 $ff |
| IGNORE    | $9387 $00 $ff | $9563 $00 $ff | $968a $00 $ff | $968a $00 $ff |
| INFO      | $f1e5 $80 $0a | $f293 $80 $0a | $f293 $80 $0a | $f29c $80 $0a |
| INSERT    | $871f $00 $ff | $874a $00 $ff | $8787 $00 $ff | $8787 $00 $ff |
| KEY       | $94c7 $00 $ff | $96a3 $00 $ff | $9713 $00 $ff | $9713 $00 $ff |
| LIBFS     | $e7f6 $00 $00 | $e926 $00 $00 | $e926 $00 $00 | $e927 $00 $00 |
| LINE      | $ec39 $00 $01 | $ecd7 $00 $01 | $ecd7 $00 $01 | $ecdf $00 $01 |
| LIST      | $8ec0 $80 $00 | $908d $80 $00 | $90ca $80 $00 | $90ca $80 $00 |
| LOAD      | $9316 $80 $00 | $94f2 $80 $00 | $952f $80 $00 | $952f $80 $00 |
| MOTOR     | $93eb $00 $89 | $ffaa $00 $89 | $ffaa $00 $89 | $ffaa $00 $89 |
| MOVE      | $90b6 $80 $00 | $928e $80 $00 | $92cb $80 $00 | $92cb $80 $00 |
| OPT       | $93eb $80 $8b | $95c7 $80 $8b | $9600 $80 $8b | $9600 $80 $8b |
| PRINT     | $8eb9 $80 $00 | $9086 $80 $00 | $90c3 $80 $00 | $90c3 $80 $00 |
| REMOVE    | $9371 $80 $00 | $954d $80 $00 | $958a $80 $00 | $958a $80 $00 |
| ROM       | $93eb $00 $8d | $95c7 $00 $8d | $9600 $00 $8d | $9600 $00 $8d |
| ROMS      | $86a6 $00 $ff | $86b9 $00 $ff | $86f6 $00 $ff | $86f6 $00 $ff |
| RUN       | $f1e5 $80 $04 | $f293 $80 $04 | $f293 $80 $04 | $f29c $80 $04 |
| SAVE      | $9318 $80 $00 | $94f4 $80 $00 | $9531 $80 $00 | $9531 $80 $00 |
| SHADOW    | $9466 $00 $ff | $9642 $00 $ff | $9638 $00 $ff | $9638 $00 $ff |
| SHOW      | $9488 $00 $ff | $9664 $00 $ff | $969e $00 $ff | $969e $00 $ff |
| SHUT      | $f373 $00 $00 | $f43f $00 $00 | $f43f $00 $00 | $f451 $00 $00 |
| SPOOL     | $9433 $80 $00 | $960f $80 $00 | $964c $80 $00 | $964c $80 $00 |
| SPOOLON   | $9420 $80 $00 | $95fc $80 $00 | $9635 $80 $00 | $9635 $80 $00 |
| SRDATA    | -             | $8cad $00 $a0 | $8cea $00 $a0 | $8cea $00 $a0 |
| SRLOAD    | -             | $8dca $80 $60 | $8e07 $80 $60 | $8e07 $80 $60 |
| SRREAD    | -             | $8d7f $00 $a0 | $8dbc $00 $a0 | $8dbc $00 $a0 |
| SRROM     | -             | $8cad $00 $80 | $8cea $00 $80 | $8cea $00 $80 |
| SRSAVE    | -             | $8dca $80 $20 | $8e07 $80 $20 | $8e07 $80 $20 |
| SRWRITE   | -             | $8d7f $00 $e0 | $8dbc $00 $e0 | $8dbc $00 $e0 |
| STATUS    | $8895 $00 $ff | $8856 $00 $c0 | $8893 $00 $c0 | $8893 $00 $c0 |
| TAPE      | $93eb $00 $8c | $ffaa $00 $8c | $ffaa $00 $8c | $ffaa $00 $8c |
| TIME      | $8744 $00 $00 | $876f $00 $00 | $87ac $00 $00 | $87ac $00 $00 |
| TV        | $93eb $00 $90 | $95c7 $00 $90 | $9600 $00 $90 | $9600 $00 $90 |
| TYPE      | $8ecb $80 $00 | $9098 $80 $00 | $90d5 $80 $00 | $90d5 $80 $00 |
| UNPLUG    | $8722 $00 $ff | $874d $00 $ff | $878a $00 $ff | $878a $00 $ff |
| X         | $e7fd $00 $00 | -             | -             | -             |
